-- CreateEnum
CREATE TYPE "Store" AS ENUM ('SPRUCEFIELD', 'MCKINSTRY', 'BANBRIDGE', 'NEWRY', 'PORTADOWN', 'LURGAN');

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "store" "Store" NOT NULL DEFAULT 'SPRUCEFIELD';

ALTER TABLE "User" ADD COLUMN "resetToken" TEXT;

ALTER TABLE "User" ADD COLUMN "resetTokenExpiry" TIMESTAMP;